import { RHFTextField } from "@root/components/hook-form";

export const crerSectionAFormData = [
  {
    id: 1,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.caringForChilds",
      label: "Caring for Children",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  ,
  {
    id: 2,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.workingWithTeam",
      label: "Working as part of a team",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 3,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.trainingAndDevelopment",
      label: "Training & Personal Development",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 4,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.carerPersonalIssue",
      label: "Carer Personal issues",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 5,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.agencyIssue",
      label: "Agency issues",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 6,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.safeCarerIssue",
      label: "Providing a Safe Enviroment / Safe Carer issues",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 7,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.commendations",
      label: "Concerns/ Allegations / Commendations",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 8,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.dayCare",
      label: "Day Care/ Household Respite Carer and Respite Training",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 9,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.fosterCarerCommments",
      label: "Foster Carer Comments on Supervision",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 10,
    gridLength: 12,
    otherOptions: {
      name: "carerSectionB.lineManagerComments",
      label: "Line Manager's Comments on Supervision",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mt: 2 },
    },
    component: RHFTextField,
  },
];
