import { RHFSelect, RHFTextField } from "@root/components/hook-form";
import RHFRadioGroupWithLabel from "@root/components/hook-form/RHFRadioGroupWithLabel";
import RHFDatePicker from "@root/components/hook-form/RHFDatePicker";

export const ChildAllegationReportsFormData = [
  {
    id: 1,
    gridLength: 6,
    otherOptions: {
      name: "urnNumber",
      label: "URN Number",
      fullWidth: true,
      sx: { mb: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 2,
    gridLength: 6,
    otherOptions: {
      name: "allegationAgainstPersonCategory",
      label: "Allegation Against Person Category",
      fullWidth: true,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFSelect,
  },
  {
    id: 3,
    gridLength: 6,
    otherOptions: {
      name: "allegationAgainstPerson",
      label: "Allegation Against Person",
      fullWidth: true,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFSelect,
  },
  {
    id: 4,
    gridLength: 6,
    otherOptions: {
      label: "Allegation Date",
      name: "allegationDate",
      fullWidth: true,
      sx: { mb: 2 },
    },
    component: RHFDatePicker,
  },
  {
    id: 5,
    gridLength: 6,
    otherOptions: {
      label: "Agency reported Date",
      name: "agencyReportedDate",
      fullWidth: true,
      sx: { mb: 2 },
    },
    component: RHFDatePicker,
  },
  {
    id: 6,
    gridLength: 6,
    otherOptions: {
      label: "Review Date",
      name: "reviewDate",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    component: RHFDatePicker,
  },
  {
    id: 7,
    gridLength: 12,
    otherOptions: {
      label: "Nature of Allegation",
      name: "natureOfAllegation",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 8,
    gridLength: 6,
    otherOptions: {
      label: "Person Notified to Agency",
      name: "personNotifiedAgency",
      fullWidth: true,
      sx: { mb: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 9,
    gridLength: 6,
    otherOptions: {
      label: "Person Completing Report",
      name: "personCompletedReport",
      fullWidth: true,
      sx: { mb: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 10,
    gridLength: 6,
    otherOptions: {
      label: "Agency Social Worker Involved",
      name: "agencySocialWorkerInvolved",
      fullWidth: true,
      sx: { mb: 2 },
    },
    component: RHFTextField,
  },
  {
    id: 11,
    gridLength: 6,
    otherOptions: {
      name: "childLocalAuthority",
      label: "Child Local Authority",
      fullWidth: true,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFSelect,
  },
  {
    id: 12,
    gridLength: 6,
    otherOptions: {
      name: "carerLocalAuthority",
      label: "Carer Local Authority",
      fullWidth: true,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFSelect,
  },
  {
    id: 13,
    gridLength: 12,
    otherOptions: {
      name: "allegationDetails",
      label: "Allegation Details",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFTextField,
  },
  {
    id: 14,
    gridLength: 12,
    otherOptions: {
      name: "investigationUndertaken",
      label: "Investigation Under Taken",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFTextField,
  },
  {
    id: 15,
    gridLength: 12,
    otherOptions: {
      name: "independentSupportInfo",
      label: "Independent Support Offered Info",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFTextField,
  },
  {
    id: 16,
    gridLength: 12,
    otherOptions: {
      name: "allegationActionTaken",
      label: "Agency Action Taken",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFTextField,
  },
  {
    id: 17,
    gridLength: 12,
    otherOptions: {
      name: "allegationOutcome",
      label: "Allegation Outcome",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFTextField,
  },
  {
    id: 18,
    gridLength: 6,
    otherOptions: {
      name: "isThisSubstained",
      label: "Is this Substantiated",
      fullWidth: true,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFSelect,
  },
  {
    id: 19,
    gridLength: 12,
    otherOptions: {
      name: "teamManagerRecommendation",
      label: "Team Manager Recommendation",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFTextField,
  },
  {
    id: 20,
    otherOptions: {
      name: "hasRegisteredManagerInformed",
      label: "Has Registered Manager Informed",
      options: ["Yes", "No"],
    },
    gridLength: 6,
    component: RHFRadioGroupWithLabel,
  },
  {
    id: 21,
    gridLength: 6,
    otherOptions: {
      label: "Registered Manager Informed Date",
      name: "registeredManagerInformedDate",
      fullWidth: true,
      sx: { mb: 2 },
    },
    component: RHFDatePicker,
  },
  {
    id: 22,
    otherOptions: {
      label: "Has Ofsted been Informed",
      name: "hasOfstedBeenInformed",
      options: ["Yes", "No"],
    },
    gridLength: 6,
    component: RHFRadioGroupWithLabel,
  },
  {
    id: 23,
    gridLength: 6,
    otherOptions: {
      label: "Ofsted Notified Date",
      name: "ofstedNotifiedDate",
      fullWidth: true,
      sx: { mb: 2 },
    },
    component: RHFDatePicker,
  },
  {
    id: 24,
    otherOptions: {
      name: "isSchedule",
      label: "is Schdule7",
      options: ["Yes", "No"],
    },
    gridLength: 6,
    component: RHFRadioGroupWithLabel,
  },
  {
    id: 25,
    gridLength: 12,
    otherOptions: {
      name: "reportedTo",
      label: "Reported To",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFTextField,
  },
  {
    id: 26,
    gridLength: 12,
    otherOptions: {
      name: "registeredManagerRecommendation",
      label: "Registered Manager Recommendation",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    options: [{ value: "xx-xx", label: "xx-xx" }],
    component: RHFTextField,
  },
  {
    id: 27,
    gridLength: 6,
    otherOptions: {
      label: "Closer Date",
      name: "closureDate",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    component: RHFDatePicker,
  },
  {
    id: 28,
    gridLength: 6,
    otherOptions: {
      label: "Next Alert Date",
      name: "nextAlertDate",
      fullWidth: true,
      multiline: true,
      minRows: 3,
      sx: { mb: 2 },
    },
    component: RHFDatePicker,
  },
];

export const defaultValuesChildAllegationReport = {
  nextAlertDate: new Date(),
  closureDate: new Date(),
  registeredManagerRecommendation: "",
  reportedTo: "",
  isSchedule: false,
  ofstedNotifiedDate: new Date(),
  hasOfstedBeenInformed: false,
  registeredManagerInformedDate: new Date(),
  hasRegisteredManagerInformed: false,
  teamManagerRecommendation: "",
  isThisSubstained: "",
  allegationOutcome: "",
  allegationActionTaken: "",
  independentSupportInfo: "",
  urnNumber: "",
  agencyReportedDate: new Date(),
  allegationAgainstPerson: "",
  allegationDate: new Date(),
  reviewDate: new Date(),
  agencySocialWorkerInvolved: "",
  natureOfAllegation: "",
  personNotifiedAgency: "",
  allegationAgainstPersonCategory: "",
  childLocalAuthority: "",
  carerLocalAuthority: "",
  allegationDetails: "",
  investigationUndertaken: "",
};
