export const data = [
    {
      id: "1",
      childName: "Draco Maldon",
      carerName: "Tom Hanks",
      dateDischarge: "12.11.2021",
      dischargeReport: "",
      approvedRole: "Album Dumbledore",
      localAuthority: "London Borough of Bexley",
      localAuthoritySW: "London Borough of Bexley",
      status: "Inprogress",
    },
    {
      id: "2",
      childName: "Draco Maldon",
      carerName: "Tom Hanks",
      dateDischarge: "12.11.2021",
      dischargeReport: "",
      approvedRole: "Album Dumbledore",
      localAuthority: "London Borough of Bexley",
      localAuthoritySW: "London Borough of Bexley",
      status: "Complete",
    },
    {
      id: "3",
      childName: "Draco Maldon",
      carerName: "Tom Hanks",
      dateDischarge: "12.11.2021",
      dischargeReport: "",
      approvedRole: "Album Dumbledore",
      localAuthority: "London Borough of Bexley",
      localAuthoritySW: "London Borough of Bexley",
      status: "Complete",
    },
    {
      id: "4",
      childName: "Draco Maldon",
      carerName: "Tom Hanks",
      dateDischarge: "12.11.2021",
      dischargeReport: "",
      approvedRole: "Album Dumbledore",
      localAuthority: "London Borough of Bexley",
      localAuthoritySW: "London Borough of Bexley",
      status: "Complete",
    },
  ];
  